import Image from "next/image";
import type { Media } from "@/payload-types";
import { getMediaUrl } from "@/library/utils";

/**
 * This component is a wrapper around Next.js Image component to handle media from Payload CMS
 * it takes care of:
 * - selecting the right size
 * - generating the correct URL
 * - handling responsive images
 * - using next/image properly with priority, quality and loading attributes
 * */

// SizeKey defines which version of the image generated by payload to use (cms side of image optimization)
type SizeKey = "thumbnail" | "card" | "hero" | "large";

// Variant defines how the image should be displayed in terms of responsiveness and cropping on the frontend (frontend side of image optimization)
type Variant = "full" | "half" | "contained" | "grid" | "auto";

export type MediaImageProps = {
    media?: Media | number | null; // payload image object, hopefully of type Media
    size?: SizeKey;
    variant?: Variant;
    fallbackAlt?: string;
    className?: string;
    wrapperClassName?: string;
    priority?: boolean; // preload (hero)
    quality?: number; // next compression level (for now I can set it on the whole image but maybe later I can set it on each size in payload)
    loading?: "lazy" | "eager"; // next loading behavior, "eager" for priority images and "lazy" for non-priority images
    withCaption?: boolean; // whether to display the caption or not, default to true
};

function getResponsive(variant: Variant, size: SizeKey) {
    switch (variant) {
        case "full": // full screen
            return "100vw";

        case "half": // half screen with cropping to keep the focus on the center of the image
            return "(max-width: 768px) 100vw, 50vw";

        case "grid": // layout 2 or 3 columns with cropping to keep the focus on the center of the image
            return "(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw";

        case "contained": // image displayed entirely, no cropping, with a max width of 800px to avoid images being too large on desktop (TODO: check with client about that)
            return "(max-width: 768px) 100vw, 800px";

        case "auto":
        default:
            // fallback based on size
            if (size === "hero") return "100vw";
            if (size === "card") return "(max-width: 768px) 100vw, 50vw";
            return "(max-width: 768px) 100vw, 800px";
    }
}

export default function MediaImage({
    media,
    size = "card",
    variant = "auto",
    fallbackAlt = "",
    className,
    wrapperClassName,
    priority = false,
    quality = 90,
    withCaption = true,
}: MediaImageProps) {
    if (!media || typeof media === "number") return null;

    const selectedSize = media.sizes?.[size];
    const filename = selectedSize?.filename || media.filename || null;
    const src = getMediaUrl(filename);

    const width = selectedSize?.width || media.width || 800;
    const height = selectedSize?.height || media.height || 600;
    const alt = media.alt || fallbackAlt;

    if (!src) return null;

    const responsive = getResponsive(variant, size);

    return (
        <div className={wrapperClassName ?? "relative"}>
            <Image
                src={src}
                alt={alt}
                width={width}
                height={height}
                className={className}
                priority={priority}
                sizes={responsive}
                quality={quality}
            />
            {withCaption && media.caption?.trim() && (
                <div className="absolute bottom-4 left-4 z-10">
                    <p className="text-xs px-1 uppercase tracking-wide text-studio-white backdrop-blur-xs bg-black/10">
                        {media.caption}
                    </p>
                </div>
            )}
        </div>
    );
}
